export const tempOrders = [
  {
    id: "A1B2C3D4",
    date: "15th December, 2024",
    itemCount: 2,
    price: 850,
    status: "in-process" as const,
    paymentMethod: "Easypaisa" as const,
  },
  {
    id: "E5F6A7B8",
    date: "3rd November, 2024",
    itemCount: 1,
    price: 299,
    status: "completed" as const,
    paymentMethod: "JazzCash" as const,
  },
  {
    id: "C9D0E1F2",
    date: "28th October, 2024",
    itemCount: 5,
    price: 2150,
    status: "completed" as const,
    paymentMethod: "Bank Account" as const,
  },
  {
    id: "A3B4C5D6",
    date: "12th September, 2024",
    itemCount: 3,
    price: 675,
    status: "completed" as const,
    paymentMethod: "Cash on Delivery" as const,
  },
  {
    id: "E7F8A9B0",
    date: "5th August, 2024",
    itemCount: 1,
    price: 199,
    status: "cancelled" as const,
    paymentMethod: "Bank Account" as const,
  },
  {
    id: "C1D2E3F4",
    date: "22nd July, 2024",
    itemCount: 7,
    price: 3420,
    status: "completed" as const,
    paymentMethod: "JazzCash" as const,
  },
  {
    id: "A5B6C7D8",
    date: "10th June, 2024",
    itemCount: 2,
    price: 540,
    status: "in-process" as const,
    paymentMethod: "JazzCash" as const,
  },
  {
    id: "E9F0A1B2",
    date: "30th May, 2024",
    itemCount: 4,
    price: 1280,
    status: "completed" as const,
    paymentMethod: "Easypaisa" as const,
  },
  {
    id: "C3D4E5F6",
    date: "18th April, 2024",
    itemCount: 1,
    price: 299,
    status: "cancelled" as const,
    paymentMethod: "Bank Account" as const,
  },
  {
    id: "A7B8C9D0",
    date: "2nd March, 2024",
    itemCount: 3,
    price: 750,
    status: "in-process" as const,
    paymentMethod: "Cash on Delivery" as const,
  },
];
